'use strict';

// 消息关键词，多个Key用KEY_SEPARATOR隔开（查询消息使用）
const PROPERTY_KEYS = 'KEYS';
// 消息标签，只支持设置一个Tag（服务端消息过滤使用）
const PROPERTY_TAGS = 'TAGS';
// 是否等待服务器将消息存储完毕再返回（可能是等待刷盘完成或者等待同步复制到其他服务器）
const PROPERTY_WAIT_STORE_MSG_OK = 'WAIT';
// 消息延时投递时间级别，0表示不延时，大于0表示特定延时级别（具体级别在服务器端定义）
const PROPERTY_DELAY_TIME_LEVEL = 'DELAY';

// 内部使用
const PROPERTY_RETRY_TOPIC = 'RETRY_TOPIC';
const PROPERTY_REAL_TOPIC = 'REAL_TOPIC';
const PROPERTY_REAL_QUEUE_ID = 'REAL_QID';
const PROPERTY_TRANSACTION_PREPARED = 'TRAN_MSG';
const PROPERTY_PRODUCER_GROUP = 'PGROUP';
const PROPERTY_MIN_OFFSET = 'MIN_OFFSET';
const PROPERTY_MAX_OFFSET = 'MAX_OFFSET';
const PROPERTY_BUYER_ID = 'BUYER_ID';
const PROPERTY_ORIGIN_MESSAGE_ID = 'ORIGIN_MESSAGE_ID';
const PROPERTY_TRANSFER_FLAG = 'TRANSFER_FLAG';
const PROPERTY_CORRECTION_FLAG = 'CORRECTION_FLAG';
const PROPERTY_MQ2_FLAG = 'MQ2_FLAG';
const PROPERTY_RECONSUME_TIME = 'RECONSUME_TIME';
const PROPERTY_MSG_REGION = 'MSG_REGION';
const PROPERTY_TRACE_SWITCH = 'TRACE_ON';
const PROPERTY_UNIQ_CLIENT_MESSAGE_ID_KEYIDX = 'UNIQ_KEY';
const PROPERTY_MAX_RECONSUME_TIMES = 'MAX_RECONSUME_TIMES';
const PROPERTY_CONSUME_START_TIMESTAMP = 'CONSUME_START_TIME';
const PROPERTY_TRANSACTION_PREPARED_QUEUE_OFFSET = 'TRAN_PREPARED_QUEUE_OFFSET';
const PROPERTY_TRANSACTION_CHECK_TIMES = 'TRANSACTION_CHECK_TIMES';
const PROPERTY_CHECK_IMMUNITY_TIME_IN_SECONDS = 'CHECK_IMMUNITY_TIME_IN_SECONDS';

const STRING_HASH_SET = new Set([
  PROPERTY_TRACE_SWITCH,
  PROPERTY_MSG_REGION,
  PROPERTY_KEYS,
  PROPERTY_TAGS,
  PROPERTY_WAIT_STORE_MSG_OK,
  PROPERTY_DELAY_TIME_LEVEL,
  PROPERTY_RETRY_TOPIC,
  PROPERTY_REAL_TOPIC,
  PROPERTY_REAL_QUEUE_ID,
  PROPERTY_TRANSACTION_PREPARED,
  PROPERTY_PRODUCER_GROUP,
  PROPERTY_MIN_OFFSET,
  PROPERTY_MAX_OFFSET,
  PROPERTY_BUYER_ID,
  PROPERTY_ORIGIN_MESSAGE_ID,
  PROPERTY_TRANSFER_FLAG,
  PROPERTY_CORRECTION_FLAG,
  PROPERTY_MQ2_FLAG,
  PROPERTY_RECONSUME_TIME,
  PROPERTY_UNIQ_CLIENT_MESSAGE_ID_KEYIDX,
  PROPERTY_MAX_RECONSUME_TIMES,
  PROPERTY_CONSUME_START_TIMESTAMP,
]);


const KEY_SEPARATOR = ' ';
const SYSTEM_PROP_KEY_STARTDELIVERTIME = '__STARTDELIVERTIME';

module.exports = {
  PROPERTY_TRACE_SWITCH,
  PROPERTY_MSG_REGION,
  PROPERTY_KEYS,
  PROPERTY_TAGS,
  PROPERTY_WAIT_STORE_MSG_OK,
  PROPERTY_DELAY_TIME_LEVEL,
  PROPERTY_RETRY_TOPIC,
  PROPERTY_REAL_TOPIC,
  PROPERTY_REAL_QUEUE_ID,
  PROPERTY_TRANSACTION_PREPARED,
  PROPERTY_PRODUCER_GROUP,
  PROPERTY_MIN_OFFSET,
  PROPERTY_MAX_OFFSET,
  PROPERTY_BUYER_ID,
  PROPERTY_ORIGIN_MESSAGE_ID,
  PROPERTY_TRANSFER_FLAG,
  PROPERTY_CORRECTION_FLAG,
  PROPERTY_MQ2_FLAG,
  PROPERTY_RECONSUME_TIME,
  PROPERTY_UNIQ_CLIENT_MESSAGE_ID_KEYIDX,
  PROPERTY_MAX_RECONSUME_TIMES,
  PROPERTY_CONSUME_START_TIMESTAMP,
  PROPERTY_TRANSACTION_PREPARED_QUEUE_OFFSET,
  PROPERTY_TRANSACTION_CHECK_TIMES,
  PROPERTY_CHECK_IMMUNITY_TIME_IN_SECONDS,
  STRING_HASH_SET,
  KEY_SEPARATOR,
  SYSTEM_PROP_KEY_STARTDELIVERTIME,
};
