'use strict';

// 消息关键词，多个Key用KEY_SEPARATOR隔开（查询消息使用）
exports.PROPERTY_KEYS = 'KEYS';
// 消息标签，只支持设置一个Tag（服务端消息过滤使用）
exports.PROPERTY_TAGS = 'TAGS';
// 是否等待服务器将消息存储完毕再返回（可能是等待刷盘完成或者等待同步复制到其他服务器）
exports.PROPERTY_WAIT_STORE_MSG_OK = 'WAIT';
// 消息延时投递时间级别，0表示不延时，大于0表示特定延时级别（具体级别在服务器端定义）
exports.PROPERTY_DELAY_TIME_LEVEL = 'DELAY';

// 内部使用
exports.PROPERTY_RETRY_TOPIC = 'RETRY_TOPIC';
exports.PROPERTY_REAL_TOPIC = 'REAL_TOPIC';
exports.PROPERTY_REAL_QUEUE_ID = 'REAL_QID';
exports.PROPERTY_TRANSACTION_PREPARED = 'TRAN_MSG';
exports.PROPERTY_PRODUCER_GROUP = 'PGROUP';
exports.PROPERTY_MIN_OFFSET = 'MIN_OFFSET';
exports.PROPERTY_MAX_OFFSET = 'MAX_OFFSET';
exports.PROPERTY_BUYER_ID = 'BUYER_ID';
exports.PROPERTY_ORIGIN_MESSAGE_ID = 'ORIGIN_MESSAGE_ID';
exports.PROPERTY_TRANSFER_FLAG = 'TRANSFER_FLAG';
exports.PROPERTY_CORRECTION_FLAG = 'CORRECTION_FLAG';
exports.PROPERTY_MQ2_FLAG = 'MQ2_FLAG';
exports.PROPERTY_RECONSUME_TIME = 'RECONSUME_TIME';
exports.PROPERTY_MAX_RECONSUME_TIMES = 'MAX_RECONSUME_TIMES';

exports.KEY_SEPARATOR = ' ';
